# Generated by Django 2.2.12 on 2022-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
