# Generated by Django 2.2.12 on 2022-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_accessrecord_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='prueba',
            field=models.IntegerField(default=222),
        ),
    ]
