# Generated by Django 2.2.12 on 2022-03-24 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220323_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('number_of_employees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=264, unique=True)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Company')),
            ],
        ),
    ]
