# Generated by Django 2.2.12 on 2022-03-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_projects_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='team_lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_reverse', to='firstapp.Employee'),
        ),
    ]
